<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function present()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('e')
            ->from('AppBundle:Event', 'e')
            ->where('e.enddate >= :datecourant')
            ->setParameter('datecourant', new \Datetime(date('d-m-Y')))
            ->orderBy('e.startdate', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }

    public function archived()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('e')
            ->from('AppBundle:Event', 'e')
            ->where('e.enddate < :datecourant')
            ->setParameter('datecourant', new \Datetime(date('d-m-Y')))
            ->orderBy('e.startdate', 'DESC');

        return $qb->getQuery()
            ->getResult();
    }
}
